services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - 1025
      - 8025:8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: MinIoUser
      MINIO_ROOT_PASSWORD: ThisIsMinIoPassword
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Create buckets at startup
  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 MinIoUser ThisIsMinIoPassword;
        mc mb --ignore-existing local/local-bucket;
        mc anonymous set download local/local-bucket;
      "

  php:
    extra_hosts:
      - "minio.eventoj.local:host-gateway"

  nginx:
    volumes:
      - ./.docker/nginx/minio.conf:/etc/nginx/conf.d/minio.conf
    command: [nginx-debug, '-g', 'daemon off;']
