version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

  maildev:
    image: maildev/maildev
    environment:
      - MAILDEV_WEB_PORT=80
      - MAILDEV_SMTP_PORT=25
    ports:
      - 1080:80
