<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250216005812 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alternative ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE alternative ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE alternative ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE alternative ALTER stations TYPE JSONB');
        $this->addSql('COMMENT ON COLUMN alternative.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN alternative.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN alternative.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN alternative.stations IS \'\'');
        $this->addSql('ALTER TABLE alternative_pictures ALTER alternative_id TYPE UUID');
        $this->addSql('ALTER TABLE alternative_pictures ALTER file_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN alternative_pictures.alternative_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN alternative_pictures.file_id IS \'\'');
        $this->addSql('ALTER TABLE companion ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE companion ALTER user_id TYPE UUID');
        $this->addSql('ALTER TABLE companion ALTER birth_date TYPE DATE');
        $this->addSql('ALTER TABLE companion ALTER phone_number TYPE VARCHAR(35)');
        $this->addSql('ALTER TABLE companion ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE companion ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN companion.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN companion.user_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN companion.birth_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN companion.phone_number IS \'\'');
        $this->addSql('COMMENT ON COLUMN companion.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN companion.updated_at IS \'\'');
        $this->addSql('ALTER TABLE event ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE event ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE event ALTER published_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE event ALTER opening_date_for_bookings TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE event ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE event ALTER uploaded_file_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN event.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN event.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN event.published_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN event.opening_date_for_bookings IS \'At which date members will be able to register to this event?\'');
        $this->addSql('COMMENT ON COLUMN event.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN event.uploaded_file_id IS \'\'');
        $this->addSql('ALTER TABLE membership ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE membership ALTER user_id TYPE UUID');
        $this->addSql('ALTER TABLE membership ALTER companion_id TYPE UUID');
        $this->addSql('ALTER TABLE membership ALTER payment_id TYPE UUID');
        $this->addSql('ALTER TABLE membership ALTER start_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE membership ALTER end_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE membership ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE membership ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE membership ALTER canceled_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN membership.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN membership.user_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN membership.companion_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN membership.payment_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN membership.start_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN membership.end_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN membership.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN membership.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN membership.canceled_at IS \'\'');
        $this->addSql('ALTER TABLE payment ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE payment ALTER payer_id TYPE UUID');
        $this->addSql('ALTER TABLE payment ALTER registration_id TYPE UUID');
        $this->addSql('ALTER TABLE payment ALTER approved_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE payment ALTER failed_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE payment ALTER refunded_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE payment ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE payment ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN payment.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN payment.payer_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN payment.registration_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN payment.approved_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN payment.failed_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN payment.refunded_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN payment.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN payment.updated_at IS \'\'');
        $this->addSql('ALTER TABLE question ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE question ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE question ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN question.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN question.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN question.updated_at IS \'\'');
        $this->addSql('ALTER TABLE registration ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE registration ALTER user_id TYPE UUID');
        $this->addSql('ALTER TABLE registration ALTER event_id TYPE UUID');
        $this->addSql('ALTER TABLE registration ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE registration ALTER confirmed_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE registration ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE registration ALTER canceled_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN registration.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN registration.user_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN registration.event_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN registration.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN registration.confirmed_at IS \'Date on which the reservation was confirmed.\'');
        $this->addSql('COMMENT ON COLUMN registration.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN registration.canceled_at IS \'Date on which the reservation was canceled.\'');
        $this->addSql('ALTER TABLE registrations_companions ALTER registration_id TYPE UUID');
        $this->addSql('ALTER TABLE registrations_companions ALTER companion_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN registrations_companions.registration_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN registrations_companions.companion_id IS \'\'');
        $this->addSql('ALTER TABLE reset_password_request ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE reset_password_request ALTER user_id TYPE UUID');
        $this->addSql('ALTER TABLE reset_password_request ALTER requested_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE reset_password_request ALTER expires_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN reset_password_request.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN reset_password_request.user_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN reset_password_request.requested_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN reset_password_request.expires_at IS \'\'');
        $this->addSql('ALTER TABLE stage ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE stage ALTER event_id TYPE UUID');
        $this->addSql('ALTER TABLE stage ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE stage ALTER date TYPE DATE');
        $this->addSql('ALTER TABLE stage ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN stage.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN stage.event_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN stage.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN stage.date IS \'\'');
        $this->addSql('COMMENT ON COLUMN stage.updated_at IS \'\'');
        $this->addSql('ALTER TABLE stages_alternatives ALTER stage_id TYPE UUID');
        $this->addSql('ALTER TABLE stages_alternatives ALTER alternative_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN stages_alternatives.stage_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN stages_alternatives.alternative_id IS \'\'');
        $this->addSql('ALTER TABLE stages_preparations ALTER stage_id TYPE UUID');
        $this->addSql('ALTER TABLE stages_preparations ALTER user_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN stages_preparations.stage_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN stages_preparations.user_id IS \'\'');
        $this->addSql('ALTER TABLE stages_registrations ALTER registration_id TYPE UUID');
        $this->addSql('ALTER TABLE stages_registrations ALTER stage_id TYPE UUID');
        $this->addSql('ALTER TABLE stages_registrations ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN stages_registrations.registration_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN stages_registrations.stage_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN stages_registrations.id IS \'\'');
        $this->addSql('ALTER TABLE uploaded_image ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE uploaded_image ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN uploaded_image.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN uploaded_image.created_at IS \'\'');
        $this->addSql('ALTER TABLE "user" ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE "user" ALTER birth_date TYPE DATE');
        $this->addSql('ALTER TABLE "user" ALTER phone_number TYPE VARCHAR(35)');
        $this->addSql('ALTER TABLE "user" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "user" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "user".id IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".birth_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".phone_number IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".updated_at IS \'\'');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "event" ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE "event" ALTER published_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "event" ALTER opening_date_for_bookings TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "event" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "event" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "event" ALTER uploaded_file_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN "event".id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "event".published_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "event".opening_date_for_bookings IS \'At which date members will be able to register to this event?(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "event".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "event".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "event".uploaded_file_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE "membership" ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE "membership" ALTER start_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "membership" ALTER end_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "membership" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "membership" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "membership" ALTER canceled_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "membership" ALTER user_id TYPE UUID');
        $this->addSql('ALTER TABLE "membership" ALTER companion_id TYPE UUID');
        $this->addSql('ALTER TABLE "membership" ALTER payment_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN "membership".id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "membership".start_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "membership".end_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "membership".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "membership".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "membership".canceled_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "membership".user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "membership".companion_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "membership".payment_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE "registration" ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE "registration" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "registration" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "registration" ALTER confirmed_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "registration" ALTER canceled_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "registration" ALTER user_id TYPE UUID');
        $this->addSql('ALTER TABLE "registration" ALTER event_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN "registration".id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "registration".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "registration".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "registration".confirmed_at IS \'Date on which the reservation was confirmed.(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "registration".canceled_at IS \'Date on which the reservation was canceled.(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "registration".user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "registration".event_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE "stages_registrations" ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE "stages_registrations" ALTER stage_id TYPE UUID');
        $this->addSql('ALTER TABLE "stages_registrations" ALTER registration_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN "stages_registrations".id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "stages_registrations".stage_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "stages_registrations".registration_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE companion ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE companion ALTER birth_date TYPE DATE');
        $this->addSql('ALTER TABLE companion ALTER phone_number TYPE VARCHAR(35)');
        $this->addSql('ALTER TABLE companion ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE companion ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE companion ALTER user_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN companion.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN companion.birth_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN companion.phone_number IS \'(DC2Type:phone_number)\'');
        $this->addSql('COMMENT ON COLUMN companion.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN companion.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN companion.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE "payment" ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE "payment" ALTER approved_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "payment" ALTER failed_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "payment" ALTER refunded_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "payment" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "payment" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "payment" ALTER payer_id TYPE UUID');
        $this->addSql('ALTER TABLE "payment" ALTER registration_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN "payment".id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "payment".approved_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "payment".failed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "payment".refunded_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "payment".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "payment".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "payment".payer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "payment".registration_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE registrations_companions ALTER registration_id TYPE UUID');
        $this->addSql('ALTER TABLE registrations_companions ALTER companion_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN registrations_companions.registration_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN registrations_companions.companion_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT messenger_messages_id_seq');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE "user" ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE "user" ALTER birth_date TYPE DATE');
        $this->addSql('ALTER TABLE "user" ALTER phone_number TYPE VARCHAR(35)');
        $this->addSql('ALTER TABLE "user" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "user" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "user".id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "user".birth_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".phone_number IS \'(DC2Type:phone_number)\'');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE "question" ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE "question" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "question" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "question".id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "question".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "question".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE "stage" ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE "stage" ALTER date TYPE DATE');
        $this->addSql('ALTER TABLE "stage" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "stage" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "stage" ALTER event_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN "stage".id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "stage".date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "stage".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "stage".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "stage".event_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE "alternative" ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE "alternative" ALTER stations TYPE jsonb');
        $this->addSql('ALTER TABLE "alternative" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "alternative" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "alternative".id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "alternative".stations IS \'(DC2Type:json_document)\'');
        $this->addSql('COMMENT ON COLUMN "alternative".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "alternative".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE stages_preparations ALTER stage_id TYPE UUID');
        $this->addSql('ALTER TABLE stages_preparations ALTER user_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN stages_preparations.stage_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN stages_preparations.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE reset_password_request ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE reset_password_request ALTER requested_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE reset_password_request ALTER expires_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE reset_password_request ALTER user_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN reset_password_request.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN reset_password_request.requested_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reset_password_request.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reset_password_request.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE alternative_pictures ALTER alternative_id TYPE UUID');
        $this->addSql('ALTER TABLE alternative_pictures ALTER file_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN alternative_pictures.alternative_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN alternative_pictures.file_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE "uploaded_image" ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE "uploaded_image" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "uploaded_image".id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "uploaded_image".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE stages_alternatives ALTER stage_id TYPE UUID');
        $this->addSql('ALTER TABLE stages_alternatives ALTER alternative_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN stages_alternatives.stage_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN stages_alternatives.alternative_id IS \'(DC2Type:uuid)\'');
    }
}
