server {
    listen 443 ssl;
    server_name minio.eventoj.local;

    ssl_certificate     /etc/nginx/certs/minio.crt;
    ssl_certificate_key /etc/nginx/certs/minio.key;

    client_max_body_size 20M;

    location / {
        proxy_pass http://minio:9000;

        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_request_buffering off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_log /var/log/nginx/minio_error.log;
    access_log /var/log/nginx/minio_access.log;
}
