on: [pull_request]
name: Tests

jobs:
  tests:
    name: PHPUnit
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:16
        env:
          POSTGRES_DB: app
          POSTGRES_PASSWORD: app
          POSTGRES_USER: app
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      minio:
        image: minio/minio:edge-cicd
        env:
          MINIO_ROOT_USER: MinIoUser
          MINIO_ROOT_PASSWORD: ThisIsMinIoPassword
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      APP_ENV: test
      APP_DEBUG: 1
      DATABASE_HOST: localhost
      S3_ENDPOINT: http://localhost:9000
      AWS_ENDPOINT_URL: http://localhost:900
      AWS_ACCESS_KEY_ID: MinIoUser
      AWS_SECRET_ACCESS_KEY: ThisIsMinIoPassword
      AWS_DEFAULT_REGION: eu-west-1

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          extensions: intl

      - name: Download dependencies
        uses: ramsey/composer-install@v4
        with:
          composer-options: "--optimize-autoloader"

      - name: Install assets
        run: bin/console importmap:install

      - name: Build assets (SASS)
        run: bin/console sass:build

      - name: Create database
        run: bin/reset-db

      - name: Create S3 bucket on MinIo
        env:
          AWS_ACCESS_KEY_ID: MinIoUser
          AWS_SECRET_ACCESS_KEY: ThisIsMinIoPassword
          AWS_DEFAULT_REGION: eu-west-1
        run: |
          aws --endpoint-url http://localhost:9000 s3 mb s3://local-bucket

      - name: Run PHPUnit
        run: bin/phpunit

      - name: Run Tiime-Software/TestedRoutesCheckerBundle
        run: bin/console bab:tested-routes-checker:check
